### ISSUE TITLE
A11y support is broken for modifiers.

### ISSUE THREAD

**Issue by adlius** [adopted-ember-addons/ember-sortable#379]
**Describe the bug**
When using the modifier, the `onChange` action is not called with correct parameters.

**To Reproduce**
I have made a [minimal app](https://github.com/adlius/ember-sortable-a11y-demo) showcasing the bug.
- Boot the app, go to `localhost:4200/`
- Open browser console
- Under the heading `Using modifiers`, reorder the items by dragging the handle, observe in the browser console that the new order and the item being reordered is correctly logged.
- Under the heading `Using modifiers`, reorder the items using the keyboard, observe in the browser console that the item being reordered is logged as `undefined`.

Just for reference, I've also added a sortable list using the addon in component form (Under the `Using component` heading). Both dragging and using keyboard to reorder works correctly.

**Expected behavior**
When using the keyboard to reorder the items, the `onChange` action should be called with 1. the list containing new order and 2. the item being reordered, instead of `undefined`.

**Additional context**
I have traced the source code a bit. It seems that the [`_complete` hook](https://github.com/adopted-ember-addons/ember-sortable/blob/master/addon/modifiers/sortable-item.js#L632) is not called when reordering using keyboard, resulting in the `SortableItemModifier`'s `wasDropped` property not set to `true`. That means in the `commit()` hook of `SortableGroupModifier`, `draggedItem` is `undefined` because [it can't find the dropped item from the list](https://github.com/adopted-ember-addons/ember-sortable/blob/master/addon/modifiers/sortable-group.js#L646).

**Comment by cah-briangantzler** [comment]
When the modifier version was created, it was a copy of all the code the component was doing, but then had to be refactored a bit. I relied heavily on the tests (because the modifier version should produce the same result.) Sounds there there are some tests that should be written that would have helped find this code was inadvertently not called.

Thanks for pointing this out, will try to get some tests in place showing the expected behaviour, then fix the code.
